name = "layspack"
author = "Kvizzz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88a50ba19f8fe8b1fb51d59326e716b00b17a4767aa628bb57aa2fca731daf18"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
